export const EMOJI_CATEGORIES = [
  { id: "recent", label: "Recent", icon: "🕐" },
  { id: "smileys", label: "Smileys", icon: "😀" },
  { id: "people", label: "People", icon: "👋" },
  { id: "animals", label: "Animals", icon: "🐶" },
  { id: "food", label: "Food", icon: "🍔" },
  { id: "travel", label: "Travel", icon: "✈️" },
  { id: "activities", label: "Activities", icon: "⚽" },
  { id: "objects", label: "Objects", icon: "💡" },
  { id: "symbols", label: "Symbols", icon: "❤️" },
  { id: "flags", label: "Flags", icon: "🏁" },
] as const;

export enum EmojiCategory {
  smileys = 1,
  people,
  animals,
  food,
  travel,
  activities,
  objects,
  symbols,
  flags,
}
export type EmojiCat =
  | "smileys"
  | "people"
  | "animals"
  | "food"
  | "travel"
  | "activities"
  | "objects"
  | "symbols"
  | "flags";

export interface EmojiEntry {
  n: string; // short name
  c: string; // character
  cat: EmojiCat;
  sk?: string; // skin tone variations (comma-separated unicode)
}

export const SKIN_TONES = ["🏻", "🏼", "🏽", "🏾", "🏿"] as const;

export const EMOJIS: EmojiEntry[] = [
  // Smileys
  { n: "grinning", c: "😀", cat: "smileys" },
  { n: "smiley", c: "😃", cat: "smileys" },
  { n: "smile", c: "😄", cat: "smileys" },
  { n: "grin", c: "😁", cat: "smileys" },
  { n: "laughing", c: "😆", cat: "smileys" },
  { n: "sweat_smile", c: "😅", cat: "smileys" },
  { n: "rofl", c: "🤣", cat: "smileys" },
  { n: "joy", c: "😂", cat: "smileys" },
  { n: "slightly_smiling", c: "🙂", cat: "smileys" },
  { n: "upside_down", c: "🙃", cat: "smileys" },
  { n: "wink", c: "😉", cat: "smileys" },
  { n: "blush", c: "😊", cat: "smileys" },
  { n: "innocent", c: "😇", cat: "smileys" },
  { n: "heart_eyes", c: "😍", cat: "smileys" },
  { n: "star_struck", c: "🤩", cat: "smileys" },
  { n: "kissing_heart", c: "😘", cat: "smileys" },
  { n: "kissing", c: "😗", cat: "smileys" },
  { n: "relaxed", c: "☺️", cat: "smileys" },
  { n: "kissing_closed_eyes", c: "😚", cat: "smileys" },
  { n: "kissing_smiling_eyes", c: "😙", cat: "smileys" },
  { n: "yum", c: "😋", cat: "smileys" },
  { n: "stuck_out_tongue", c: "😛", cat: "smileys" },
  { n: "stuck_out_tongue_winking_eye", c: "😜", cat: "smileys" },
  { n: "zany_face", c: "🤪", cat: "smileys" },
  { n: "stuck_out_tongue_closed_eyes", c: "😝", cat: "smileys" },
  { n: "money_mouth", c: "🤑", cat: "smileys" },
  { n: "hugging_face", c: "🤗", cat: "smileys" },
  { n: "hand_over_mouth", c: "🤭", cat: "smileys" },
  { n: "shushing_face", c: "🤫", cat: "smileys" },
  { n: "thinking", c: "🤔", cat: "smileys" },
  { n: "zipper_mouth", c: "🤐", cat: "smileys" },
  { n: "raised_eyebrow", c: "🤨", cat: "smileys" },
  { n: "neutral", c: "😐", cat: "smileys" },
  { n: "expressionless", c: "😑", cat: "smileys" },
  { n: "no_mouth", c: "😶", cat: "smileys" },
  { n: "smirk", c: "😏", cat: "smileys" },
  { n: "unamused", c: "😒", cat: "smileys" },
  { n: "roll_eyes", c: "🙄", cat: "smileys" },
  { n: "grimacing", c: "😬", cat: "smileys" },
  { n: "lying_face", c: "🤥", cat: "smileys" },
  { n: "relieved", c: "😌", cat: "smileys" },
  { n: "pensive", c: "😔", cat: "smileys" },
  { n: "sleepy", c: "😪", cat: "smileys" },
  { n: "drooling_face", c: "🤤", cat: "smileys" },
  { n: "sleeping", c: "😴", cat: "smileys" },
  { n: "mask", c: "😷", cat: "smileys" },
  { n: "face_with_thermometer", c: "🤒", cat: "smileys" },
  { n: "face_with_head_bandage", c: "🤕", cat: "smileys" },
  { n: "nauseated", c: "🤢", cat: "smileys" },
  { n: "vomiting", c: "🤮", cat: "smileys" },
  { n: "sneeze", c: "🤧", cat: "smileys" },
  { n: "hot_face", c: "🥵", cat: "smileys" },
  { n: "cold_face", c: "🥶", cat: "smileys" },
  { n: "woozy", c: "🥴", cat: "smileys" },
  { n: "dizzy_face", c: "😵", cat: "smileys" },
  { n: "exploding_head", c: "🤯", cat: "smileys" },
  { n: "cowboy", c: "🤠", cat: "smileys" },
  { n: "partying", c: "🥳", cat: "smileys" },
  { n: "sunglasses", c: "😎", cat: "smileys" },
  { n: "nerd", c: "🤓", cat: "smileys" },
  { n: "monocle", c: "🧐", cat: "smileys" },
  { n: "confused", c: "😕", cat: "smileys" },
  { n: "worried", c: "😟", cat: "smileys" },
  { n: "slightly_frowning", c: "🙁", cat: "smileys" },
  { n: "frowning", c: "☹️", cat: "smileys" },
  { n: "open_mouth", c: "😮", cat: "smileys" },
  { n: "hushed", c: "😯", cat: "smileys" },
  { n: "astonished", c: "😲", cat: "smileys" },
  { n: "flushed", c: "😳", cat: "smileys" },
  { n: "pleading", c: "🥺", cat: "smileys" },
  { n: "frowning_face", c: "😦", cat: "smileys" },
  { n: "anguished", c: "😧", cat: "smileys" },
  { n: "fearful", c: "😨", cat: "smileys" },
  { n: "cold_sweat", c: "😰", cat: "smileys" },
  { n: "disappointed_relieved", c: "😥", cat: "smileys" },
  { n: "cry", c: "😢", cat: "smileys" },
  { n: "sob", c: "😭", cat: "smileys" },
  { n: "scream", c: "😱", cat: "smileys" },
  { n: "confounded", c: "😖", cat: "smileys" },
  { n: "persevere", c: "😣", cat: "smileys" },
  { n: "disappointed", c: "😞", cat: "smileys" },
  { n: "sweat", c: "😓", cat: "smileys" },
  { n: "weary", c: "😩", cat: "smileys" },
  { n: "tired_face", c: "😫", cat: "smileys" },
  { n: "yawning", c: "🥱", cat: "smileys" },
  { n: "triumph", c: "😤", cat: "smileys" },
  { n: "rage", c: "😡", cat: "smileys" },
  { n: "angry", c: "😠", cat: "smileys" },
  { n: "cursing", c: "🤬", cat: "smileys" },
  { n: "smiling_imp", c: "😈", cat: "smileys" },
  { n: "imp", c: "👿", cat: "smileys" },
  { n: "skull", c: "💀", cat: "smileys" },
  { n: "skull_crossbones", c: "☠️", cat: "smileys" },
  { n: "poop", c: "💩", cat: "smileys" },
  { n: "clown", c: "🤡", cat: "smileys" },
  { n: "japanese_ogre", c: "👹", cat: "smileys" },
  { n: "japanese_goblin", c: "👺", cat: "smileys" },
  { n: "ghost", c: "👻", cat: "smileys" },
  { n: "alien", c: "👽", cat: "smileys" },
  { n: "robot", c: "🤖", cat: "smileys" },
  { n: "smiley_cat", c: "😺", cat: "smileys" },
  { n: "smile_cat", c: "😸", cat: "smileys" },
  { n: "joy_cat", c: "😹", cat: "smileys" },
  { n: "heart_eyes_cat", c: "😻", cat: "smileys" },
  { n: "smirk_cat", c: "😼", cat: "smileys" },
  { n: "kissing_cat", c: "😽", cat: "smileys" },
  { n: "scream_cat", c: "🙀", cat: "smileys" },
  { n: "crying_cat", c: "😿", cat: "smileys" },
  { n: "pouting_cat", c: "😾", cat: "smileys" },
  { n: "see_no_evil", c: "🙈", cat: "smileys" },
  { n: "hear_no_evil", c: "🙉", cat: "smileys" },
  { n: "speak_no_evil", c: "🙊", cat: "smileys" },

  // People
  { n: "wave", c: "👋", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "raised_back_of_hand", c: "🤚", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "raised_hand", c: "✋", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "vulcan_salute", c: "🖖", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "ok_hand", c: "👌", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "pinched_fingers", c: "🤌", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "pinching_hand", c: "🤏", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "v", c: "✌️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "crossed_fingers", c: "🤞", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "love_you_gesture", c: "🤟", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "metal", c: "🤘", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "call_me", c: "🤙", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "point_left", c: "👈", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "point_right", c: "👉", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "point_up", c: "👆", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "middle_finger", c: "🖕", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "point_down", c: "👇", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "point_up_2", c: "☝️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "+1", c: "👍", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "-1", c: "👎", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "fist", c: "✊", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "facepunch", c: "👊", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "left_facing_fist", c: "🤛", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "right_facing_fist", c: "🤜", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "clap", c: "👏", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "raised_hands", c: "🙌", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "heart_hands", c: "🫶", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "open_hands", c: "👐", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "palms_up_together", c: "🤲", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "handshake", c: "🤝", cat: "people" },
  { n: "pray", c: "🙏", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "writing_hand", c: "✍️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "nail_care", c: "💅", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "selfie", c: "🤳", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "muscle", c: "💪", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "mechanical_arm", c: "🦾", cat: "people" },
  { n: "leg", c: "🦵", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "foot", c: "🦶", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "ear", c: "👂", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "nose", c: "👃", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "brain", c: "🧠", cat: "people" },
  { n: "tooth", c: "🦷", cat: "people" },
  { n: "tongue", c: "👅", cat: "people" },
  { n: "lips", c: "👄", cat: "people" },
  { n: "baby", c: "👶", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "child", c: "🧒", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "boy", c: "👦", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "girl", c: "👧", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "adult", c: "🧑", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "man", c: "👨", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "woman", c: "👩", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "older_adult", c: "🧓", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "older_man", c: "👴", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "older_woman", c: "👵", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_blond_hair", c: "👱", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "man_with_beard", c: "🧔", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "red_haired", c: "🦰", cat: "people" },
  { n: "curly_haired", c: "🦱", cat: "people" },
  { n: "bald", c: "🦲", cat: "people" },
  { n: "white_haired", c: "🦳", cat: "people" },
  { n: "police_officer", c: "👮", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "construction_worker", c: "👷", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "prince", c: "🤴", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "princess", c: "👸", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_wearing_turban", c: "👳", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_with_headscarf", c: "🧕", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_in_tuxedo", c: "🤵", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "bride_with_veil", c: "👰", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_feeding_baby", c: "🍼", cat: "people" },
  { n: "angel", c: "👼", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "santa", c: "🎅", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "mrs_claus", c: "🤶", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "superhero", c: "🦸", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "supervillain", c: "🦹", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "mage", c: "🧙", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "fairy", c: "🧚", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "vampire", c: "🧛", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "merperson", c: "🧜", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "elf", c: "🧝", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "genie", c: "🧞", cat: "people" },
  { n: "zombie", c: "🧟", cat: "people" },
  { n: "person_getting_massage", c: "💆", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_getting_haircut", c: "💇", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "walking", c: "🚶", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "running", c: "🏃", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "dancer", c: "💃", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "man_dancing", c: "🕺", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "people_with_bunny_ears", c: "👯", cat: "people" },
  { n: "person_in_steamy_room", c: "🧖", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_climbing", c: "🧗", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_fencing", c: "🤺", cat: "people" },
  { n: "horse_racing", c: "🏇", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "skier", c: "⛷️", cat: "people" },
  { n: "snowboarder", c: "🏂", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "golfing", c: "🏌️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "surfer", c: "🏄", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "rowboat", c: "🚣", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "swimmer", c: "🏊", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "bouncing_ball", c: "⛹️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "weight_lifter", c: "🏋️", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "bicyclist", c: "🚴", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "mountain_bicyclist", c: "🚵", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "person_doing_cartwheel", c: "🤸", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "wrestlers", c: "🤼", cat: "people" },
  { n: "water_polo", c: "🤽", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "handball", c: "🤾", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "juggling", c: "🤹", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "lotus_position", c: "🧘", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "bath", c: "🛀", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "sleeping_accommodation", c: "🛌", cat: "people", sk: "1f3fb,1f3fc,1f3fd,1f3fe,1f3ff" },
  { n: "couple", c: "💑", cat: "people" },
  { n: "family", c: "👪", cat: "people" },

  // Animals
  { n: "dog", c: "🐶", cat: "animals" },
  { n: "cat", c: "🐱", cat: "animals" },
  { n: "mouse", c: "🐭", cat: "animals" },
  { n: "hamster", c: "🐹", cat: "animals" },
  { n: "rabbit", c: "🐰", cat: "animals" },
  { n: "fox", c: "🦊", cat: "animals" },
  { n: "bear", c: "🐻", cat: "animals" },
  { n: "panda", c: "🐼", cat: "animals" },
  { n: "koala", c: "🐨", cat: "animals" },
  { n: "tiger", c: "🐯", cat: "animals" },
  { n: "lion", c: "🦁", cat: "animals" },
  { n: "cow", c: "🐮", cat: "animals" },
  { n: "pig", c: "🐷", cat: "animals" },
  { n: "frog", c: "🐸", cat: "animals" },
  { n: "monkey", c: "🐵", cat: "animals" },
  { n: "chicken", c: "🐔", cat: "animals" },
  { n: "penguin", c: "🐧", cat: "animals" },
  { n: "bird", c: "🐦", cat: "animals" },
  { n: "baby_chick", c: "🐤", cat: "animals" },
  { n: "hatching_chick", c: "🐣", cat: "animals" },
  { n: "hatched_chick", c: "🐥", cat: "animals" },
  { n: "duck", c: "🦆", cat: "animals" },
  { n: "eagle", c: "🦅", cat: "animals" },
  { n: "owl", c: "🦉", cat: "animals" },
  { n: "bat", c: "🦇", cat: "animals" },
  { n: "wolf", c: "🐺", cat: "animals" },
  { n: "boar", c: "🐗", cat: "animals" },
  { n: "horse", c: "🐴", cat: "animals" },
  { n: "unicorn", c: "🦄", cat: "animals" },
  { n: "bee", c: "🐝", cat: "animals" },
  { n: "bug", c: "🐛", cat: "animals" },
  { n: "butterfly", c: "🦋", cat: "animals" },
  { n: "snail", c: "🐌", cat: "animals" },
  { n: "ladybug", c: "🐞", cat: "animals" },
  { n: "ant", c: "🐜", cat: "animals" },
  { n: "mosquito", c: "🦟", cat: "animals" },
  { n: "scorpion", c: "🦂", cat: "animals" },
  { n: "turtle", c: "🐢", cat: "animals" },
  { n: "snake", c: "🐍", cat: "animals" },
  { n: "lizard", c: "🦎", cat: "animals" },
  { n: "t_rex", c: "🦖", cat: "animals" },
  { n: "sauropod", c: "🦕", cat: "animals" },
  { n: "octopus", c: "🐙", cat: "animals" },
  { n: "squid", c: "🦑", cat: "animals" },
  { n: "shrimp", c: "🦐", cat: "animals" },
  { n: "lobster", c: "🦞", cat: "animals" },
  { n: "crab", c: "🦀", cat: "animals" },
  { n: "blowfish", c: "🐡", cat: "animals" },
  { n: "tropical_fish", c: "🐠", cat: "animals" },
  { n: "fish", c: "🐟", cat: "animals" },
  { n: "dolphin", c: "🐬", cat: "animals" },
  { n: "whale", c: "🐳", cat: "animals" },
  { n: "whale2", c: "🐋", cat: "animals" },
  { n: "crocodile", c: "🐊", cat: "animals" },
  { n: "leopard", c: "🐆", cat: "animals" },
  { n: "tiger2", c: "🐅", cat: "animals" },
  { n: "water_buffalo", c: "🐃", cat: "animals" },
  { n: "ox", c: "🐂", cat: "animals" },
  { n: "cow2", c: "🐄", cat: "animals" },
  { n: "ram", c: "🐏", cat: "animals" },
  { n: "goat", c: "🐐", cat: "animals" },
  { n: "rooster", c: "🐓", cat: "animals" },
  { n: "dog2", c: "🐕", cat: "animals" },
  { n: "poodle", c: "🐩", cat: "animals" },
  { n: "cat2", c: "🐈", cat: "animals" },
  { n: "rabbit2", c: "🐇", cat: "animals" },
  { n: "chipmunk", c: "🐿️", cat: "animals" },
  { n: "hedgehog", c: "🦔", cat: "animals" },
  { n: "raccoon", c: "🦝", cat: "animals" },
  { n: "llama", c: "🦙", cat: "animals" },
  { n: "giraffe", c: "🦒", cat: "animals" },
  { n: "elephant", c: "🐘", cat: "animals" },
  { n: "rhinoceros", c: "🦏", cat: "animals" },
  { n: "gorilla", c: "🦍", cat: "animals" },
  { n: "monkey_face", c: "🐒", cat: "animals" },
  { n: "kangaroo", c: "🦘", cat: "animals" },
  { n: "zebra", c: "🦓", cat: "animals" },
  { n: "parrot", c: "🦜", cat: "animals" },
  { n: "peacock", c: "🦚", cat: "animals" },
  { n: "swan", c: "🦢", cat: "animals" },
  { n: "flamingo", c: "🦩", cat: "animals" },
  { n: "sloth", c: "🦥", cat: "animals" },
  { n: "otter", c: "🦦", cat: "animals" },
  { n: "skunk", c: "🦨", cat: "animals" },

  // Food
  { n: "apple", c: "🍎", cat: "food" },
  { n: "green_apple", c: "🍏", cat: "food" },
  { n: "pear", c: "🍐", cat: "food" },
  { n: "orange", c: "🍊", cat: "food" },
  { n: "lemon", c: "🍋", cat: "food" },
  { n: "banana", c: "🍌", cat: "food" },
  { n: "watermelon", c: "🍉", cat: "food" },
  { n: "grapes", c: "🍇", cat: "food" },
  { n: "strawberry", c: "🍓", cat: "food" },
  { n: "blueberries", c: "🫐", cat: "food" },
  { n: "cherries", c: "🍒", cat: "food" },
  { n: "peach", c: "🍑", cat: "food" },
  { n: "mango", c: "🥭", cat: "food" },
  { n: "pineapple", c: "🍍", cat: "food" },
  { n: "coconut", c: "🥥", cat: "food" },
  { n: "kiwi", c: "🥝", cat: "food" },
  { n: "tomato", c: "🍅", cat: "food" },
  { n: "eggplant", c: "🍆", cat: "food" },
  { n: "avocado", c: "🥑", cat: "food" },
  { n: "broccoli", c: "🥦", cat: "food" },
  { n: "leafy_greens", c: "🥬", cat: "food" },
  { n: "cucumber", c: "🥒", cat: "food" },
  { n: "hot_pepper", c: "🌶️", cat: "food" },
  { n: "corn", c: "🌽", cat: "food" },
  { n: "carrot", c: "🥕", cat: "food" },
  { n: "potato", c: "🥔", cat: "food" },
  { n: "sweet_potato", c: "🍠", cat: "food" },
  { n: "bread", c: "🍞", cat: "food" },
  { n: "croissant", c: "🥐", cat: "food" },
  { n: "bagel", c: "🥯", cat: "food" },
  { n: "pretzel", c: "🥨", cat: "food" },
  { n: "cheese", c: "🧀", cat: "food" },
  { n: "egg", c: "🥚", cat: "food" },
  { n: "cooking", c: "🍳", cat: "food" },
  { n: "pancakes", c: "🥞", cat: "food" },
  { n: "waffle", c: "🧇", cat: "food" },
  { n: "bacon", c: "🥓", cat: "food" },
  { n: "hamburger", c: "🍔", cat: "food" },
  { n: "fries", c: "🍟", cat: "food" },
  { n: "pizza", c: "🍕", cat: "food" },
  { n: "hotdog", c: "🌭", cat: "food" },
  { n: "sandwich", c: "🥪", cat: "food" },
  { n: "taco", c: "🌮", cat: "food" },
  { n: "burrito", c: "🌯", cat: "food" },
  { n: "falafel", c: "🧆", cat: "food" },
  { n: "sushi", c: "🍣", cat: "food" },
  { n: "rice", c: "🍚", cat: "food" },
  { n: "curry", c: "🍛", cat: "food" },
  { n: "ramen", c: "🍜", cat: "food" },
  { n: "spaghetti", c: "🍝", cat: "food" },
  { n: "doughnut", c: "🍩", cat: "food" },
  { n: "cookie", c: "🍪", cat: "food" },
  { n: "cake", c: "🎂", cat: "food" },
  { n: "cupcake", c: "🧁", cat: "food" },
  { n: "pie", c: "🥧", cat: "food" },
  { n: "chocolate", c: "🍫", cat: "food" },
  { n: "candy", c: "🍬", cat: "food" },
  { n: "lollipop", c: "🍭", cat: "food" },
  { n: "ice_cream", c: "🍦", cat: "food" },
  { n: "shaved_ice", c: "🍧", cat: "food" },
  { n: "icecream", c: "🍨", cat: "food" },
  { n: "coffee", c: "☕", cat: "food" },
  { n: "tea", c: "🍵", cat: "food" },
  { n: "wine_glass", c: "🍷", cat: "food" },
  { n: "beer", c: "🍺", cat: "food" },
  { n: "beers", c: "🍻", cat: "food" },
  { n: "cocktail", c: "🍸", cat: "food" },
  { n: "tropical_drink", c: "🍹", cat: "food" },
  { n: "champagne", c: "🥂", cat: "food" },
  { n: "sake", c: "🍶", cat: "food" },

  // Travel
  { n: "car", c: "🚗", cat: "travel" },
  { n: "taxi", c: "🚕", cat: "travel" },
  { n: "bus", c: "🚌", cat: "travel" },
  { n: "truck", c: "🚚", cat: "travel" },
  { n: "bike", c: "🚲", cat: "travel" },
  { n: "scooter", c: "🛴", cat: "travel" },
  { n: "motorcycle", c: "🏍️", cat: "travel" },
  { n: "airplane", c: "✈️", cat: "travel" },
  { n: "rocket", c: "🚀", cat: "travel" },
  { n: "helicopter", c: "🚁", cat: "travel" },
  { n: "train", c: "🚆", cat: "travel" },
  { n: "metro", c: "🚇", cat: "travel" },
  { n: "tram", c: "🚊", cat: "travel" },
  { n: "ship", c: "🚢", cat: "travel" },
  { n: "anchor", c: "⚓", cat: "travel" },
  { n: "house", c: "🏠", cat: "travel" },
  { n: "house_with_garden", c: "🏡", cat: "travel" },
  { n: "office", c: "🏢", cat: "travel" },
  { n: "post_office", c: "🏣", cat: "travel" },
  { n: "hospital", c: "🏥", cat: "travel" },
  { n: "bank", c: "🏦", cat: "travel" },
  { n: "school", c: "🏫", cat: "travel" },
  { n: "supermarket", c: "🏪", cat: "travel" },
  { n: "factory", c: "🏭", cat: "travel" },
  { n: "castle", c: "🏰", cat: "travel" },
  { n: "church", c: "⛪", cat: "travel" },
  { n: "mosque", c: "🕌", cat: "travel" },
  { n: "synagogue", c: "🕍", cat: "travel" },
  { n: "statue_of_liberty", c: "🗽", cat: "travel" },
  { n: "eiffel_tower", c: "🗼", cat: "travel" },
  { n: "fountain", c: "⛲", cat: "travel" },
  { n: "tent", c: "⛺", cat: "travel" },
  { n: "sunrise", c: "🌅", cat: "travel" },
  { n: "sunset", c: "🌇", cat: "travel" },
  { n: "cityscape", c: "🌃", cat: "travel" },
  { n: "night_with_stars", c: "🌙", cat: "travel" },
  { n: "beach", c: "🏖️", cat: "travel" },
  { n: "desert", c: "🏜️", cat: "travel" },
  { n: "island", c: "🏝️", cat: "travel" },
  { n: "mountain", c: "⛰️", cat: "travel" },
  { n: "volcano", c: "🌋", cat: "travel" },
  { n: "camping", c: "🏕️", cat: "travel" },
  { n: "snow_capped_mountain", c: "🏔️", cat: "travel" },
  { n: "railway_track", c: "🛤️", cat: "travel" },
  { n: "road", c: "🛣️", cat: "travel" },
  { n: "bridge_at_night", c: "🌉", cat: "travel" },

  // Activities
  { n: "soccer", c: "⚽", cat: "activities" },
  { n: "basketball", c: "🏀", cat: "activities" },
  { n: "football", c: "🏈", cat: "activities" },
  { n: "baseball", c: "⚾", cat: "activities" },
  { n: "tennis", c: "🎾", cat: "activities" },
  { n: "volleyball", c: "🏐", cat: "activities" },
  { n: "rugby", c: "🏉", cat: "activities" },
  { n: "pool_8", c: "🎱", cat: "activities" },
  { n: "ping_pong", c: "🏓", cat: "activities" },
  { n: "badminton", c: "🏸", cat: "activities" },
  { n: "golf", c: "⛳", cat: "activities" },
  { n: "fishing", c: "🎣", cat: "activities" },
  { n: "bowling", c: "🎳", cat: "activities" },
  { n: "video_game", c: "🎮", cat: "activities" },
  { n: "game_die", c: "🎲", cat: "activities" },
  { n: "chess", c: "♟️", cat: "activities" },
  { n: "dart", c: "🎯", cat: "activities" },
  { n: "bow_and_arrow", c: "🏹", cat: "activities" },
  { n: "snowboarder_act", c: "🏂", cat: "activities" },
  { n: "parachute", c: "🪂", cat: "activities" },
  { n: "surfing", c: "🏄", cat: "activities" },
  { n: "swimming", c: "🏊", cat: "activities" },
  { n: "weight_lifting", c: "🏋️", cat: "activities" },
  { n: "gymnastics", c: "🤸", cat: "activities" },
  { n: "martial_arts", c: "🥋", cat: "activities" },
  { n: "boxing_glove", c: "🥊", cat: "activities" },
  { n: "running_shirt", c: "🎽", cat: "activities" },
  { n: "medal", c: "🏅", cat: "activities" },
  { n: "trophy", c: "🏆", cat: "activities" },
  { n: "rosette", c: "🏵️", cat: "activities" },
  { n: "ticket", c: "🎫", cat: "activities" },
  { n: "performing_arts", c: "🎭", cat: "activities" },
  { n: "art", c: "🎨", cat: "activities" },
  { n: "clapper", c: "🎬", cat: "activities" },
  { n: "microphone", c: "🎤", cat: "activities" },
  { n: "headphones", c: "🎧", cat: "activities" },
  { n: "musical_score", c: "🎼", cat: "activities" },
  { n: "musical_keyboard", c: "🎹", cat: "activities" },
  { n: "drum", c: "🥁", cat: "activities" },
  { n: "saxophone", c: "🎷", cat: "activities" },
  { n: "trumpet", c: "🎺", cat: "activities" },
  { n: "guitar", c: "🎸", cat: "activities" },
  { n: "violin", c: "🎻", cat: "activities" },
  { n: "party_popper", c: "🎉", cat: "activities" },
  { n: "balloon", c: "🎈", cat: "activities" },
  { n: "confetti", c: "🎊", cat: "activities" },
  { n: "tada", c: "🎉", cat: "activities" },
  { n: "sparkler", c: "🎇", cat: "activities" },
  { n: "fireworks", c: "🎆", cat: "activities" },
  { n: "ribbon", c: "🎀", cat: "activities" },
  { n: "gift", c: "🎁", cat: "activities" },
  { n: "jack_o_lantern", c: "🎃", cat: "activities" },
  { n: "christmas_tree", c: "🎄", cat: "activities" },

  // Objects
  { n: "glasses", c: "👓", cat: "objects" },
  { n: "sunglasses_obj", c: "🕶️", cat: "objects" },
  { n: "shirt", c: "👕", cat: "objects" },
  { n: "jeans", c: "👖", cat: "objects" },
  { n: "dress", c: "👗", cat: "objects" },
  { n: "kimono", c: "👘", cat: "objects" },
  { n: "bikini", c: "👙", cat: "objects" },
  { n: "purse", c: "👛", cat: "objects" },
  { n: "handbag", c: "👜", cat: "objects" },
  { n: "backpack", c: "🎒", cat: "objects" },
  { n: "shoe", c: "👞", cat: "objects" },
  { n: "boot", c: "👢", cat: "objects" },
  { n: "crown", c: "👑", cat: "objects" },
  { n: "ring", c: "💍", cat: "objects" },
  { n: "gem", c: "💎", cat: "objects" },
  { n: "computer", c: "💻", cat: "objects" },
  { n: "keyboard", c: "⌨️", cat: "objects" },
  { n: "printer", c: "🖨️", cat: "objects" },
  { n: "mouse_three", c: "🖱️", cat: "objects" },
  { n: "phone", c: "📱", cat: "objects" },
  { n: "telephone", c: "☎️", cat: "objects" },
  { n: "fax", c: "📠", cat: "objects" },
  { n: "battery", c: "🔋", cat: "objects" },
  { n: "electric_plug", c: "🔌", cat: "objects" },
  { n: "bulb", c: "💡", cat: "objects" },
  { n: "flashlight", c: "🔦", cat: "objects" },
  { n: "candle", c: "🕯️", cat: "objects" },
  { n: "fire", c: "🔥", cat: "objects" },
  { n: "trash", c: "🗑️", cat: "objects" },
  { n: "book", c: "📖", cat: "objects" },
  { n: "newspaper", c: "📰", cat: "objects" },
  { n: "pencil", c: "✏️", cat: "objects" },
  { n: "pen", c: "🖊️", cat: "objects" },
  { n: "paperclip", c: "📎", cat: "objects" },
  { n: "scissors", c: "✂️", cat: "objects" },
  { n: "lock", c: "🔒", cat: "objects" },
  { n: "key", c: "🔑", cat: "objects" },
  { n: "hammer", c: "🔨", cat: "objects" },
  { n: "wrench", c: "🔧", cat: "objects" },
  { n: "screwdriver", c: "🪛", cat: "objects" },
  { n: "gear", c: "⚙️", cat: "objects" },
  { n: "microscope", c: "🔬", cat: "objects" },
  { n: "telescope", c: "🔭", cat: "objects" },
  { n: "satellite", c: "📡", cat: "objects" },
  { n: "syringe", c: "💉", cat: "objects" },
  { n: "pill", c: "💊", cat: "objects" },
  { n: "moneybag", c: "💰", cat: "objects" },
  { n: "dollar", c: "💵", cat: "objects" },
  { n: "credit_card", c: "💳", cat: "objects" },
  { n: "envelope", c: "✉️", cat: "objects" },
  { n: "mailbox", c: "📫", cat: "objects" },
  { n: "package", c: "📦", cat: "objects" },
  { n: "clock", c: "🕐", cat: "objects" },
  { n: "alarm_clock", c: "⏰", cat: "objects" },
  { n: "hourglass", c: "⌛", cat: "objects" },
  { n: "camera", c: "📷", cat: "objects" },
  { n: "video_camera", c: "📹", cat: "objects" },
  { n: "television", c: "📺", cat: "objects" },
  { n: "radio", c: "📻", cat: "objects" },
  { n: "loud_sound", c: "🔊", cat: "objects" },
  { n: "bell", c: "🔔", cat: "objects" },
  { n: "musical_note", c: "🎵", cat: "objects" },
  { n: "notes", c: "🎶", cat: "objects" },
  { n: "wrench_obj", c: "🔧", cat: "objects" },
  { n: "hammer_and_wrench", c: "🛠️", cat: "objects" },
  { n: "nut_and_bolt", c: "🔩", cat: "objects" },
  { n: "bomb", c: "💣", cat: "objects" },
  { n: "smoking", c: "🚬", cat: "objects" },

  // Symbols
  { n: "heart", c: "❤️", cat: "symbols" },
  { n: "orange_heart", c: "🧡", cat: "symbols" },
  { n: "yellow_heart", c: "💛", cat: "symbols" },
  { n: "green_heart", c: "💚", cat: "symbols" },
  { n: "blue_heart", c: "💙", cat: "symbols" },
  { n: "purple_heart", c: "💜", cat: "symbols" },
  { n: "black_heart", c: "🖤", cat: "symbols" },
  { n: "white_heart", c: "🤍", cat: "symbols" },
  { n: "brown_heart", c: "🤎", cat: "symbols" },
  { n: "broken_heart", c: "💔", cat: "symbols" },
  { n: "heart_exclamation", c: "❣️", cat: "symbols" },
  { n: "two_hearts", c: "💕", cat: "symbols" },
  { n: "sparkling_heart", c: "💖", cat: "symbols" },
  { n: "heartpulse", c: "💗", cat: "symbols" },
  { n: "cupid", c: "💘", cat: "symbols" },
  { n: "gift_heart", c: "💝", cat: "symbols" },
  { n: "revolving_hearts", c: "💞", cat: "symbols" },
  { n: "heartbeat", c: "💓", cat: "symbols" },
  { n: "100", c: "💯", cat: "symbols" },
  { n: "anger", c: "💢", cat: "symbols" },
  { n: "boom", c: "💥", cat: "symbols" },
  { n: "dizzy", c: "💫", cat: "symbols" },
  { n: "sweat_drops", c: "💦", cat: "symbols" },
  { n: "dash", c: "💨", cat: "symbols" },
  { n: "hole", c: "🕳️", cat: "symbols" },
  { n: "speech_balloon", c: "💬", cat: "symbols" },
  { n: "thought_balloon", c: "💭", cat: "symbols" },
  { n: "white_check_mark", c: "✅", cat: "symbols" },
  { n: "x", c: "❌", cat: "symbols" },
  { n: "check", c: "✔️", cat: "symbols" },
  { n: "cross", c: "✖️", cat: "symbols" },
  { n: "plus", c: "➕", cat: "symbols" },
  { n: "minus", c: "➖", cat: "symbols" },
  { n: "division", c: "➗", cat: "symbols" },
  { n: "arrow_up", c: "⬆️", cat: "symbols" },
  { n: "arrow_down", c: "⬇️", cat: "symbols" },
  { n: "arrow_left", c: "⬅️", cat: "symbols" },
  { n: "arrow_right", c: "➡️", cat: "symbols" },
  { n: "arrows_clockwise", c: "🔃", cat: "symbols" },
  { n: "arrows_counterclockwise", c: "🔄", cat: "symbols" },
  { n: "recycle", c: "♻️", cat: "symbols" },
  { n: "warning", c: "⚠️", cat: "symbols" },
  { n: "no_entry", c: "🚫", cat: "symbols" },
  { n: "no_smoking", c: "🚭", cat: "symbols" },
  { n: "wheelchair", c: "♿", cat: "symbols" },
  { n: "parking", c: "🅿️", cat: "symbols" },
  { n: "restroom", c: "🚻", cat: "symbols" },
  { n: "wc", c: "🚾", cat: "symbols" },
  { n: "potable_water", c: "🚰", cat: "symbols" },
  { n: "phone_symbol", c: "📞", cat: "symbols" },
  { n: "atm", c: "🏧", cat: "symbols" },
  { n: "signal_strength", c: "📶", cat: "symbols" },
  { n: "cinema", c: "🎦", cat: "symbols" },
  { n: "mute", c: "🔇", cat: "symbols" },
  { n: "speaker", c: "🔈", cat: "symbols" },
  { n: "sound", c: "🔉", cat: "symbols" },
  { n: "loudspeaker", c: "📢", cat: "symbols" },
  { n: "mega", c: "📣", cat: "symbols" },
  { n: "infinity", c: "♾️", cat: "symbols" },
  { n: "peace", c: "☮️", cat: "symbols" },
  { n: "yin_yang", c: "☯️", cat: "symbols" },
  { n: "hash", c: "#️⃣", cat: "symbols" },
  { n: "keycap_star", c: "*️⃣", cat: "symbols" },
  { n: "zero", c: "0️⃣", cat: "symbols" },
  { n: "one", c: "1️⃣", cat: "symbols" },
  { n: "two", c: "2️⃣", cat: "symbols" },
  { n: "three", c: "3️⃣", cat: "symbols" },
  { n: "four", c: "4️⃣", cat: "symbols" },
  { n: "five", c: "5️⃣", cat: "symbols" },
  { n: "six", c: "6️⃣", cat: "symbols" },
  { n: "seven", c: "7️⃣", cat: "symbols" },
  { n: "eight", c: "8️⃣", cat: "symbols" },
  { n: "nine", c: "9️⃣", cat: "symbols" },
  { n: "ten", c: "🔟", cat: "symbols" },
  { n: "copyright", c: "©️", cat: "symbols" },
  { n: "registered", c: "®️", cat: "symbols" },
  { n: "tm", c: "™️", cat: "symbols" },

  // Flags
  { n: "checkered_flag", c: "🏁", cat: "flags" },
  { n: "triangular_flag", c: "🚩", cat: "flags" },
  { n: "crossed_flags", c: "🎌", cat: "flags" },
  { n: "black_flag", c: "🏴", cat: "flags" },
  { n: "white_flag", c: "🏳️", cat: "flags" },
  { n: "rainbow_flag", c: "🏳️‍🌈", cat: "flags" },
  { n: "united_nations", c: "🇺🇳", cat: "flags" },
  { n: "us", c: "🇺🇸", cat: "flags" },
  { n: "uk", c: "🇬🇧", cat: "flags" },
  { n: "canada", c: "🇨🇦", cat: "flags" },
  { n: "australia", c: "🇦🇺", cat: "flags" },
  { n: "japan", c: "🇯🇵", cat: "flags" },
  { n: "germany", c: "🇩🇪", cat: "flags" },
  { n: "france", c: "🇫🇷", cat: "flags" },
  { n: "italy", c: "🇮🇹", cat: "flags" },
  { n: "spain", c: "🇪🇸", cat: "flags" },
  { n: "brazil", c: "🇧🇷", cat: "flags" },
  { n: "india", c: "🇮🇳", cat: "flags" },
  { n: "china", c: "🇨🇳", cat: "flags" },
  { n: "south_korea", c: "🇰🇷", cat: "flags" },
  { n: "russia", c: "🇷🇺", cat: "flags" },
  { n: "mexico", c: "🇲🇽", cat: "flags" },
  { n: "netherlands", c: "🇳🇱", cat: "flags" },
  { n: "sweden", c: "🇸🇪", cat: "flags" },
  { n: "norway", c: "🇳🇴", cat: "flags" },
  { n: "denmark", c: "🇩🇰", cat: "flags" },
  { n: "finland", c: "🇫🇮", cat: "flags" },
  { n: "poland", c: "🇵🇱", cat: "flags" },
  { n: "argentina", c: "🇦🇷", cat: "flags" },
  { n: "south_africa", c: "🇿🇦", cat: "flags" },
  { n: "switzerland", c: "🇨🇭", cat: "flags" },
  { n: "ireland", c: "🇮🇪", cat: "flags" },
  { n: "portugal", c: "🇵🇹", cat: "flags" },
  { n: "turkey", c: "🇹🇷", cat: "flags" },
  { n: "greece", c: "🇬🇷", cat: "flags" },
  { n: "israel", c: "🇮🇱", cat: "flags" },
  { n: "egypt", c: "🇪🇬", cat: "flags" },
  { n: "nigeria", c: "🇳🇬", cat: "flags" },
  { n: "kenya", c: "🇰🇪", cat: "flags" },
  { n: "thailand", c: "🇹🇭", cat: "flags" },
  { n: "vietnam", c: "🇻🇳", cat: "flags" },
  { n: "philippines", c: "🇵🇭", cat: "flags" },
  { n: "indonesia", c: "🇮🇩", cat: "flags" },
  { n: "malaysia", c: "🇲🇾", cat: "flags" },
  { n: "new_zealand", c: "🇳🇿", cat: "flags" },
  { n: "puerto_rico", c: "🇵🇷", cat: "flags" },
  { n: "jamaica", c: "🇯🇲", cat: "flags" },
  { n: "cuba", c: "🇨🇺", cat: "flags" },
];
