"""
Generate all 4 platform audit prompt output JSON files and ingest them.
"""
import json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(r"C:\temp\chat")
OUTPUTS = REPO / "tmp_prompt_outputs"
INGEST = REPO / "scripts" / "prompts" / "ingest_output.py"
now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

prompts = []

# ============================================================
# 1. Final Reconciliation — Repo Audit (Step 1, stage: reconciliation)
# ============================================================
prompts.append({
    "prompt_name": "final_reconciliation_repo_audit",
    "domain": "reconciliation",
    "stage": "reconciliation",
    "decision": "GO WITH RISKS",
    "generated_at": now,
    "severity_counts": {"P0": 1, "P1": 3, "P2": 4, "P3": 3},
    "category_scores": {"env_drift": 70, "import_errors": 85, "dead_files": 60, "naming_consistency": 75, "phase_contracts": 65},
    "readiness": 71.0,
    "findings": [
        {"severity": "P0", "domain": "reconciliation", "category": "phase_contracts",
         "file": "apps/api/src/modules/feature-flags/routes.ts",
         "issue": "Feature-flag routes reference requireWorkspaceMembership('workspaceId') but no :workspaceId param exists in route path — every request returns 400",
         "impact": "Feature flags completely non-functional; all workspace feature-flag operations silently fail",
         "fix": "Remove requireWorkspaceMembership or add workspaceId as a body/query parameter"},
        {"severity": "P1", "domain": "reconciliation", "category": "env_drift",
         "file": "apps/api/src/config/env.ts",
         "issue": "API env schema uses EMAIL_FROM while shared packages/config/env-schema.ts uses SMTP_FROM — same purpose, different env var names",
         "impact": "Operators may set SMTP_FROM expecting it to be read, but API reads EMAIL_FROM and falls back silently",
         "fix": "Standardize on a single name (EMAIL_FROM), update shared schema to match"},
        {"severity": "P1", "domain": "reconciliation", "category": "env_drift",
         "file": "apps/web/lib/env.ts",
         "issue": "Web env schema missing NEXT_PUBLIC_SENTRY_DSN, NEXT_PUBLIC_APP_VERSION, NEXT_PUBLIC_GIT_SHA, NEXT_PUBLIC_BUILD_TIME — all used in code but not validated",
         "impact": "Version badge shows '0.0.0-dev' and 'local' in production; Sentry not configured on frontend",
         "fix": "Add missing vars to apps/web/lib/env.ts Zod schema"},
        {"severity": "P1", "domain": "reconciliation", "category": "naming_consistency",
         "file": "infra/terraform/versions.tf",
         "issue": "Terraform state key is hardcoded with no environment interpolation — same state key for dev and prod",
         "impact": "Parallel dev and prod Terraform operations corrupt each other's state",
         "fix": "Use ${var.environment} in state key to isolate environments"},
        {"severity": "P2", "domain": "reconciliation", "category": "dead_files",
         "file": "docs/runbooks/database-migrations.md",
         "issue": "Runbook references packages/db/sql/migrations/ directory which no longer exists — all migrations consolidated under supabase/migrations/",
         "impact": "Operators following runbook will look in wrong directory for migration files",
         "fix": "Update runbook to reference supabase/migrations/ as the single source of migrations"},
        {"severity": "P2", "domain": "reconciliation", "category": "dead_files",
         "file": "",
         "issue": "Duplicate policy file sets exist: docs/hardening_super_bundle/policies/ and docs/audits/policies/ — risk of drift",
         "impact": "Policy changes may be applied to one set but not the other; inconsistent gating",
         "fix": "Consolidate to single source of truth (hardening/policies/) and remove duplicates"},
        {"severity": "P2", "domain": "reconciliation", "category": "naming_consistency",
         "file": "",
         "issue": "Migration sequence gap in 20260626 batch — jumps from 01 to 22 suggesting deleted or renumbered migrations",
         "impact": "Potential confusion about migration history; Supabase CLI tracking may conflict",
         "fix": "Audit migration sequence; renumber or add placeholder files to fill gaps"},
        {"severity": "P2", "domain": "reconciliation", "category": "phase_contracts",
         "file": "apps/api/src/modules/webhooks/routes.ts",
         "issue": "Webhook GET route reads workspace_id from query param but middleware checks req.params.workspaceId — they never match",
         "impact": "Webhook listing bypasses workspace membership check via query param",
         "fix": "Create middleware that reads from req.query.workspace_id instead of req.params"},
        {"severity": "P3", "domain": "reconciliation", "category": "naming_consistency",
         "file": "infra/docker/Caddyfile.prod",
         "issue": "Production Caddyfile missing API subdomain block for chat-api.mainecybertech.com — DNS record exists but Caddy does not serve it",
         "impact": "Wasted DNS record; direct API subdomain access gets no response",
         "fix": "Remove unused DNS record or add Caddy site block for completeness"},
        {"severity": "P3", "domain": "reconciliation", "category": "env_drift",
         "file": "infra/terraform/variables.tf",
         "issue": "Default droplet size still s-1vcpu-512mb-10gb despite known OOM issues — AGENTS.md documents upgrade to s-2vcpu-2gb",
         "impact": "New dev droplets provisioned with undersized spec will experience OOM",
         "fix": "Update default droplet_size to s-2vcpu-2gb in terraform variables.tf"},
        {"severity": "P3", "domain": "reconciliation", "category": "dead_files",
         "file": "docs/audits/",
         "issue": "Stale index (2).md file found in dashboard directory — appears to be a duplicate from a copy conflict",
         "impact": "Git tracking noise; confusing for maintainers",
         "fix": "Remove duplicate index (2).md file"}
    ]
})

# ============================================================
# 2. Final Reconciliation — Principal Audit (Step 2, stage: principal_audit)
# ============================================================
prompts.append({
    "prompt_name": "final_reconciliation_principal_audit",
    "domain": "principal_audit",
    "stage": "principal_audit",
    "decision": "NO-GO",
    "generated_at": now,
    "severity_counts": {"P0": 5, "P1": 8, "P2": 10, "P3": 8},
    "category_scores": {
        "A Monorepo Workspace Package Governance": 85,
        "B TypeScript Build Import Integrity": 72,
        "C Frontend Backend Database Contract Alignment": 50,
        "D Authentication Authorization Security Surface": 35,
        "E Environment Domain Consistency": 60,
        "F API Realtime Socket Correctness": 45,
        "G Frontend Routing UX State Provider Integrity": 65,
        "H UXUI Design Quality": 55,
        "I Accessibility Readiness": 55,
        "J Responsive Readiness": 50,
        "K Quality Tooling Test Validation Infrastructure": 20,
        "L CICD GitHub Environments Release Automation": 60,
        "M Docker Caddy Runtime Orchestration": 75,
        "N Terraform Cloud-Init Host Provisioning": 70,
        "O Documentation Runbooks Contributor Guidance": 65,
        "P Dead Files Duplicate Systems Stale Artifacts": 70
    },
    "readiness": 57.0,
    "findings": [
        {"severity": "P0", "domain": "principal_audit", "category": "D Security Surface",
         "file": "apps/api/src/modules/reactions/routes.ts",
         "issue": "Reaction routes have no workspace/channel membership check — any authenticated user can access any message's reactions cross-tenant",
         "impact": "Cross-tenant data access: User A can add/remove reactions on any message in any workspace without membership",
         "fix": "Add requireChannelAccess middleware to all reaction routes"},
        {"severity": "P0", "domain": "principal_audit", "category": "D Security Surface",
         "file": "supabase/migrations/",
         "issue": "SECURITY DEFINER functions (handle_new_user, handle_new_channel, handle_new_workspace) missing SET search_path",
         "impact": "Search_path injection: user with CREATE privilege can hijack these functions for privilege escalation",
         "fix": "Add SET search_path = 'public' to all SECURITY DEFINER function definitions"},
        {"severity": "P0", "domain": "principal_audit", "category": "C Contract Alignment",
         "file": "apps/api/src/modules/messages/routes.ts",
         "issue": "Message search uses getSupabase() (anon client) instead of req.supabase (JWT client) — auth.uid() is NULL",
         "impact": "search_messages RPC cannot verify workspace membership; cross-tenant message content leak",
         "fix": "Replace getSupabase() with req.supabase on messages/routes.ts line 38"},
        {"severity": "P0", "domain": "principal_audit", "category": "F API Socket Correctness",
         "file": "apps/api/src/lib/socket.ts",
         "issue": "No per-event Socket.io authorization — any connected client can join any channel room via channel:join",
         "impact": "Socket-based tenant isolation bypass: attacker can listen to any channel's real-time events",
         "fix": "Add membership check in channel:join handler before adding socket to room"},
        {"severity": "P0", "domain": "principal_audit", "category": "K Quality Tooling",
         "file": "tests/",
         "issue": "Zero E2E test coverage for any critical user flow — all 48 comprehensive E2E tests are skipped/test.skip",
         "impact": "No automated regression detection for any user journey; every deploy blind",
         "fix": "Build auth, workspace, and messaging E2E tests as Tier 0 smoke tests running on every PR"},
        {"severity": "P1", "domain": "principal_audit", "category": "C Contract Alignment",
         "file": "packages/db/src/types.ts",
         "issue": "TypeScript types severely out of sync with DB schema — 6 interfaces vs 16 tables; soft-delete fields missing",
         "impact": "Type safety gaps across codebase; developers forced to use 'any' for many operations",
         "fix": "Regenerate types via supabase gen types typescript; add CI drift check"},
        {"severity": "P1", "domain": "principal_audit", "category": "D Security Surface",
         "file": "apps/api/src/modules/workspaces/routes.ts",
         "issue": "Workspace member management lacks admin/owner role check — any workspace member can add/remove/change roles",
         "impact": "Privilege escalation: member can self-promote to admin or remove other members",
         "fix": "Add admin/owner role verification in member management routes"},
        {"severity": "P1", "domain": "principal_audit", "category": "D Security Surface",
         "file": "apps/api/src/lib/socket.ts",
         "issue": "Socket.io allowEIO3: true enables Engine.IO v3 legacy protocol with known vulnerabilities",
         "impact": "Expanded attack surface on real-time transport layer",
         "fix": "Set allowEIO3: false unless backward compatibility is required"},
        {"severity": "P1", "domain": "principal_audit", "category": "E Environment Consistency",
         "file": ".github/workflows/supabase-migrations.yml",
         "issue": "Same SUPABASE_PROJECT_REF used for both dev and prod — no separate Supabase project per environment",
         "impact": "Migrations from develop branch directly affect the same database as main",
         "fix": "Use separate Supabase projects with separate project ref secrets per environment"},
        {"severity": "P1", "domain": "principal_audit", "category": "K Quality Tooling",
         "file": "tests/k6/",
         "issue": "k6 load tests only hit / and /healthz — no real endpoints tested; not integrated into CI",
         "impact": "Load tests provide zero insight into actual system performance under load",
         "fix": "Add meaningful k6 test scenarios for message send, search, and WebSocket connect; run in CI"},
        {"severity": "P1", "domain": "principal_audit", "category": "I Accessibility Readiness",
         "file": "apps/web/",
         "issue": "No tablet-specific breakpoint — layout jumps from 3-column desktop to single-column mobile at 768px",
         "impact": "Tablet users receive suboptimal layout; no progressive collapse",
         "fix": "Add 1024px breakpoint with collapsed sidebar drawer pattern"},
        {"severity": "P1", "domain": "principal_audit", "category": "L CICD Automation",
         "file": ".github/workflows/deploy-production.yml",
         "issue": "No production approval gate — push to main immediately deploys without manual review",
         "impact": "Any merge to main can deploy to production with zero human oversight",
         "fix": "Add environment: production with required reviewers to deploy job"},
        {"severity": "P1", "domain": "principal_audit", "category": "P Dead Files",
         "file": ".github/workflows/governance.yml",
         "issue": "governance.yml and platform.yml workflows are broken — reference 5 nonexistent scripts (full_engine.ps1, auto_fix.ps1, etc.)",
         "impact": "CI noise on every push; no actual governance enforcement",
         "fix": "Fix or disable broken workflows; consolidate into working evaluate_gate.py invocations"},
        {"severity": "P2", "domain": "principal_audit", "category": "A Monorepo Governance",
         "file": "",
         "issue": "Worker package (apps/worker/) has no test script, no health endpoint, no observability — completely unmonitored",
         "impact": "Worker failures invisible until users report symptoms",
         "fix": "Add vitest config, health endpoint, and basic logging/metrics to worker package"},
        {"severity": "P2", "domain": "principal_audit", "category": "C Contract Alignment",
         "file": "infra/docker/Caddyfile.prod",
         "issue": "Prod Caddyfile only has /health route; dev Caddyfile has /healthz and /health* and API subdomain — inconsistency",
         "impact": "Health check path ambiguity between environments could cause deploy failures",
         "fix": "Standardize health endpoints across both Caddyfiles; match Docker HEALTHCHECK paths"},
        {"severity": "P2", "domain": "principal_audit", "category": "F API Socket Correctness",
         "file": "apps/api/src/modules/channels/service.ts",
         "issue": "Channel slug dedup loop has no max-attempt safety guard unlike workspace MAX_ATTEMPTS=100",
         "impact": "Infinite loop on slug collision; potential DoS vector",
         "fix": "Add MAX_ATTEMPTS=100 guard to channel slug dedup"},
        {"severity": "P2", "domain": "principal_audit", "category": "G Frontend Routing UX",
         "file": "",
         "issue": "All pages use 'use client' — no React Server Components; no route-level code splitting",
         "impact": "Full JS bundle on every page; no streaming SSR benefit",
         "fix": "Convert non-interactive sections to server components; use next/dynamic for heavy components"},
        {"severity": "P2", "domain": "principal_audit", "category": "J Responsive Readiness",
         "file": "",
         "issue": "No mobile bottom navigation bar — every context switch requires opening sidebar",
         "impact": "Mobile navigation requires 3+ taps; poor one-handed UX",
         "fix": "Add mobile bottom tab bar with workspace, channels, notifications, search, user menu"},
        {"severity": "P2", "domain": "principal_audit", "category": "M Docker Orchestration",
         "file": ".github/workflows/deploy-production.yml",
         "issue": "docker system prune -af --volumes destroys previous SHA-tagged images before health check succeeds",
         "impact": "If deploy fails, previous rollback target images are already deleted",
         "fix": "Move prune to after successful health check"},
        {"severity": "P3", "domain": "principal_audit", "category": "B TypeScript Integrity",
         "file": "",
         "issue": "No shared API contract types between frontend and backend — types are manually duplicated",
         "impact": "Frontend/backend contract drift causes silent production failures",
         "fix": "Create packages/contract/ with shared API request/response types"},
        {"severity": "P3", "domain": "principal_audit", "category": "H UXUI Design Quality",
         "file": "",
         "issue": "Unicode/emoji characters used as icons throughout — no icon library",
         "impact": "Inconsistent cross-platform rendering; no accessibility support for icons",
         "fix": "Migrate to lucide-react SVG icons with aria-hidden and aria-label"},
        {"severity": "P3", "domain": "principal_audit", "category": "N Terraform Provisioning",
         "file": "infra/terraform/main.tf",
         "issue": "DigitalOcean alerts (CPU>80%, Memory>80%) only go to email — no Slack, PagerDuty, or SMS",
         "impact": "Critical infrastructure alerts may go unnoticed",
         "fix": "Add Slack webhook integration to DO monitoring alert channel"},
        {"severity": "P3", "domain": "principal_audit", "category": "O Documentation",
         "file": "",
         "issue": "No keyboard shortcut help documentation — users cannot discover keyboard shortcuts",
         "impact": "Productivity features go unused",
         "fix": "Add keyboard shortcut reference in settings; add Ctrl+/ help overlay"}
    ]
})

# ============================================================
# 3. Deep-Dive Quality Confirmation (Step 3, stage: quality_confirmation)
# ============================================================
prompts.append({
    "prompt_name": "deep_dive_quality_confirmation",
    "domain": "quality_confirmation",
    "stage": "quality_confirmation",
    "decision": "NO-GO",
    "generated_at": now,
    "severity_counts": {"P0": 3, "P1": 4, "P2": 4, "P3": 3},
    "category_scores": {
        "Integration Coverage": 50,
        "Error Handling": 55,
        "Graceful Degradation": 35,
        "State Consistency": 50,
        "Audit Completeness": 60,
        "Defense-in-Depth": 45,
        "Migration Safety": 40
    },
    "readiness": 48.0,
    "findings": [
        {"severity": "P0", "domain": "quality_confirmation", "category": "Graceful Degradation",
         "file": "apps/api/src/modules/messages/service.ts",
         "issue": "No request timeout on any Supabase query — slow DB can block Node event loop indefinitely, causing complete API outage",
         "impact": "30s DB query latency blocks all request threads; entire API becomes unresponsive; no circuit breaker to give recovery time",
         "fix": "Add AbortSignal.timeout(10000) to all Supabase queries; wrap Supabase client in circuit breaker"},
        {"severity": "P0", "domain": "quality_confirmation", "category": "State Consistency",
         "file": "apps/api/src/lib/socket.ts",
         "issue": "Socket.io has no connection state recovery — clients lose all room memberships on reconnect; no offline message queue",
         "impact": "Messages sent during disconnect window are lost; after reconnect, clients must manually re-join each channel",
         "fix": "Enable connectionStateRecovery; implement client-side reconnection with exponential backoff; add message queue flush on reconnect"},
        {"severity": "P0", "domain": "quality_confirmation", "category": "Error Handling",
         "file": "apps/web/components/chat/chat-view.tsx",
         "issue": "No global error boundary around workspace/channel content — uncaught React errors show blank page with no recovery action",
         "impact": "Any unhandled React error in chat components results in a completely blank UI; user must manually refresh",
         "fix": "Add ErrorBoundary wrapper with 'Try Again' button around chat content area"},
        {"severity": "P1", "domain": "quality_confirmation", "category": "Integration Coverage",
         "file": "apps/api/src/modules/webhooks/routes.ts",
         "issue": "Webhook GET route reads workspace_id from query param but middleware reads req.params — query param never checked for authorization",
         "impact": "Webhook listing endpoint bypasses workspace membership validation",
         "fix": "Add query parameter reading middleware or move workspace_id to route param"},
        {"severity": "P1", "domain": "quality_confirmation", "category": "Error Handling",
         "file": "apps/api/src/modules/notifications/service.ts",
         "issue": "Push notification delivery failures use console.error instead of structured logger.error",
         "impact": "Push failures invisible in centralized logging; no ability to alert on failure rates",
         "fix": "Replace console.error with logger.error including structured context (notification type, user agent, error code)"},
        {"severity": "P1", "domain": "quality_confirmation", "category": "Defense-in-Depth",
         "file": ".github/workflows/deploy-production.yml",
         "issue": "Cloudflare origin cert and private key written to disk via echo heredoc in CI/CD — secret exposure risk",
         "impact": "TLS private key could appear in CI logs on shell failure; compromises TLS security for production domain",
         "fix": "Use GitHub Actions env file ($GITHUB_ENV) for secrets; avoid echo-based file writing"},
        {"severity": "P1", "domain": "quality_confirmation", "category": "Audit Completeness",
         "file": "apps/api/src/modules/auth/routes.ts",
         "issue": "GDPR delete route does not clean up audit_logs or consent_logs — user's audit trail persists after account deletion",
         "impact": "GDPR Right to Erasure partially implemented; user data remains in audit and consent tables",
         "fix": "Add explicit deletion of audit_logs and consent_logs entries for the deleted user"},
        {"severity": "P2", "domain": "quality_confirmation", "category": "Integration Coverage",
         "file": "infra/docker/docker-compose.prod.yml",
         "issue": "No Redis container defined in production Docker compose — REDIS_URL is configured but no Redis service exists",
         "impact": "Redis-dependent features (idempotency, socket adapter, rate limiting) silently fall back to in-memory mode",
         "fix": "Add Redis service to docker-compose.prod.yml or document that Redis is an external managed service"},
        {"severity": "P2", "domain": "quality_confirmation", "category": "State Consistency",
         "file": "apps/api/src/lib/idempotency.ts",
         "issue": "In-memory idempotency fallback has no LRU eviction or max size — unbounded memory growth under high message volume",
         "impact": "Potential OOM on burst traffic patterns",
         "fix": "Add LRU eviction with max 10000 entries to in-memory Map"},
        {"severity": "P2", "domain": "quality_confirmation", "category": "Audit Completeness",
         "file": "apps/api/src/services/audit.ts",
         "issue": "Audit event queue is in-memory with no persistence — events lost on process restart",
         "impact": "Audit trail gaps during deploy/hotfix windows",
         "fix": "Replace in-memory queue with Redis-backed persistent queue"},
        {"severity": "P2", "domain": "quality_confirmation", "category": "Migration Safety",
         "file": "supabase/migrations/",
         "issue": "No down/rollback scripts exist for any of 26 migrations — forward-fix is the only recovery path",
         "impact": "Migration rollback requires PITR with data loss instead of simple SQL reversal",
         "fix": "Write .down.sql scripts for all migrations; mandate down scripts for all future migrations"},
        {"severity": "P3", "domain": "quality_confirmation", "category": "Integration Coverage",
         "file": "",
         "issue": "No distributed tracing — only basic request IDs; no OpenTelemetry span propagation across services",
         "impact": "Cannot trace a single user action across API -> DB -> WebSocket -> webhook",
         "fix": "Add OpenTelemetry for Express, Supabase queries, and outbound HTTP calls"},
        {"severity": "P3", "domain": "quality_confirmation", "category": "Error Handling",
         "file": "",
         "issue": "Frontend has no structured logging — console.log/error used ad-hoc with no format",
         "impact": "Client-side errors cannot be diagnosed from logs",
         "fix": "Add frontend logging library with remote log shipping for production errors"},
        {"severity": "P3", "domain": "quality_confirmation", "category": "Defense-in-Depth",
         "file": "apps/api/src/lib/feature-flags.ts",
         "issue": "Feature flag service uses getSupabaseAdmin() for ALL operations including reads — bypasses RLS",
         "impact": "Overprivileged data access pattern; RLS cannot restrict feature flag reads",
         "fix": "Use req.supabase for reads, getSupabaseAdmin() only for writes"}
    ]
})

# ============================================================
# 4. Environment Promotion Audit (stage: principal_audit)
# ============================================================
prompts.append({
    "prompt_name": "environment_promotion_audit",
    "domain": "environment",
    "stage": "principal_audit",
    "decision": "NO-GO",
    "generated_at": now,
    "severity_counts": {"P0": 2, "P1": 3, "P2": 2, "P3": 2},
    "category_scores": {"domains": 55, "caddy_tls": 60, "secrets": 40, "health_endpoints": 65, "resource_limits": 50, "image_tags": 60, "backup_config": 20},
    "readiness": 50.0,
    "findings": [
        {"severity": "P0", "domain": "environment", "category": "domains",
         "file": "infra/terraform/versions.tf",
         "issue": "Terraform state key hardcoded without environment interpolation — dev and prod share the same state file",
         "impact": "Parallel Terraform operations for dev and prod will corrupt state; irreversible state conflicts on concurrent applies",
         "fix": "Use ${var.environment} in backend key to isolate environment state"},
        {"severity": "P0", "domain": "environment", "category": "secrets",
         "file": ".github/workflows/supabase-migrations.yml",
         "issue": "Same SUPABASE_PROJECT_REF secret for dev and prod — no separate Supabase project per environment",
         "impact": "Migrations applied from develop branch directly target the same database as main branch migrations",
         "fix": "Create separate Supabase projects for dev and prod; add separate secret names"},
        {"severity": "P1", "domain": "environment", "category": "caddy_tls",
         "file": "infra/docker/Caddyfile.prod",
         "issue": "Prod Caddyfile only has /health route for health checks; dev Caddyfile has /healthz and /health* with API subdomain",
         "impact": "Health check routing differs between environments — deployment validation may succeed in dev but fail in prod",
         "fix": "Standardize health endpoints: add /healthz and /health* handle_path to prod Caddyfile"},
        {"severity": "P1", "domain": "environment", "category": "secrets",
         "file": ".github/workflows/",
         "issue": "SMTP/email env vars not configured in any deployment workflow — SMTP_HOST/PORT/USER/PASS and EMAIL_FROM all missing",
         "impact": "Password reset and transactional emails non-functional in both dev and prod environments",
         "fix": "Add SMTP configuration secrets to all deploy workflows; validate at deploy time"},
        {"severity": "P1", "domain": "environment", "category": "backup_config",
         "file": "",
         "issue": "No backup/restore procedure documented for production — Supabase PITR is the only recovery option but undocumented",
         "impact": "Production data recovery during incident requires guessing procedures; no documented RTO/RPO",
         "fix": "Create docs/runbooks/backup-restore.md with PITR procedure, storage backup, and DR runbook"},
        {"severity": "P2", "domain": "environment", "category": "resource_limits",
         "file": "infra/terraform/variables.tf",
         "issue": "Default droplet size s-1vcpu-512mb-10gb known to OOM — documented in AGENTS.md but not updated in Terraform",
         "impact": "New dev droplets provision at undersized spec; OOM under normal load",
         "fix": "Update default droplet_size to s-2vcpu-2gb in variables.tf"},
        {"severity": "P2", "domain": "environment", "category": "image_tags",
         "file": ".github/workflows/deploy-production.yml",
         "issue": "Production version badge build-args not passed — NEXT_PUBLIC_APP_VERSION, NEXT_PUBLIC_GIT_SHA, NEXT_PUBLIC_BUILD_TIME omitted",
         "impact": "Production always shows 'v0.0.0-dev' and 'local'; cannot identify deployed version from badge",
         "fix": "Add NEXT_PUBLIC_APP_VERSION=${{ github.ref_name }}-${{ github.run_number }}, NEXT_PUBLIC_GIT_SHA, NEXT_PUBLIC_BUILD_TIME to web Docker build"},
        {"severity": "P3", "domain": "environment", "category": "domains",
         "file": "",
         "issue": "Dev API subdomain (chat-api.mainecybertech.us) deployed but unused — DNS + Caddy block exist but nothing consumes it",
         "impact": "Wasted TLS cert, DNS record, and Caddy config; all API traffic goes through same-domain /v1/* proxy",
         "fix": "Remove unused API subdomain DNS record for development; document as future option"},
        {"severity": "P3", "domain": "environment", "category": "health_endpoints",
         "file": "",
         "issue": "No external uptime monitoring for production — only Docker HEALTHCHECK and deploy-time validation",
         "impact": "Production downtime detected only when users report it or email alerts trigger for CPU/memory",
         "fix": "Add free-tier uptime monitoring (UptimeRobot or Better Uptime) checking /healthz every 5 minutes"}
    ]
})

# ============================================================
# WRITE ALL FILES AND INGEST
# ============================================================
for p in prompts:
    name = p["prompt_name"]
    path = OUTPUTS / f"{name}.json"
    path.write_text(json.dumps(p, indent=2, default=str), encoding="utf-8")
    print(f"Written: {path.name} ({len(p['findings'])} findings, P0={p['severity_counts']['P0']})")

print(f"\nTotal: {len(prompts)} prompts")

# Ingest each
print("\n--- Ingesting ---")
for p in prompts:
    name = p["prompt_name"]
    path = OUTPUTS / f"{name}.json"
    result = subprocess.run(
        [sys.executable, str(INGEST), "--prompt-name", name, "--output-file", str(path)],
        capture_output=True, text=True, cwd=str(REPO)
    )
    if result.returncode == 0:
        parsed = json.loads(result.stdout)
        print(f"  {name}: OK (run_id={parsed['run_id']}, findings={parsed['finding_count']})")
    else:
        print(f"  {name}: FAILED - {result.stderr.strip()}")
